#ifndef BASEMODULE_CPP
#define BASEMODULE_CPP
#include "DataPOJO.h"
#include "BaseModule.h"
#include<random>
#include<future>
#include<thread>
using namespace std;

//Default constructor of class BaseModule
BaseModule::BaseModule()
{
	this->data = new DataPOJO();
}

//This Method is the required run() method according to the assignment.
//It has two parameters:
//-> first one is promise that will store and return the value as a DataPOJO Object when the task is completed
//-> second one is the seed that is used by PRNG of this Module and is generated by the PRNG in main
void BaseModule::run(promise<DataPOJO*> p,long long seed)
{
	long long temp;//Just a temporary value
	mt19937 generator (seed);//the PRNG of this Module
	this->data->setName("BaseModule");
	temp=generator();
	this->data->setFirst(temp);
	temp=generator();
	this->data->setSecond(temp);
	p.set_value(this->data);
}
#endif
