#ifndef DATAPOJO_CPP
#define DATAPOJO_CPP
#include "DataPOJO.h"
DataPOJO::DataPOJO(){} //Default constructor of class DataPOJO

//Paramaterized constructor of DataPOJO class for initializing its members
DataPOJO::DataPOJO(long long first,long long second,char* name)
{
	this->first=first;
	this->second=second;
	this->name=name;
}

//setter method to set first number generated by PRNG in a module
void DataPOJO::setFirst(long long first)
{
	this->first=first;
}

//setter method to set second number generated by PRNG in a module
void DataPOJO::setSecond(long long second)
{
	this->second=second;
}

//setter method to set name of the module
void DataPOJO::setName(char* name)
{
	this->name=name;
}

//getter method to get first number generated by PRNG in a module
long long DataPOJO::getFirst()
{
	return this->first;
}

//getter method to get second number generated by PRNG in a module
long long DataPOJO::getSecond()
{
	return this->second;
}

//getter method to get name of the module
char* DataPOJO::getName()
{
	return this->name;
}
#endif
