#ifndef MODULE2_CPP
#define MODULE2_CPP
#include "DataPOJO.h"
#include "BaseModule.h"
#include "Module2.h"
#include<random>
#include<future>
#include<thread>
using namespace std;

//Default constructor of class BaseModule
Module2::Module2()
{
	this->data = new DataPOJO();
}

//This Method is the required overridden run() method according to the assignment.
//It has two parameters:
//-> first one is promise that will store and return the value as a DataPOJO Object when the task is completed
//-> second one is the seed that is used by PRNG of this Module and is generated by the PRNG in main
void Module2::run(promise<DataPOJO*> p,long long seed)
{
	long long temp;//just a temporary value
	mt19937 generator (seed);//the PRNG of this Module
	this->data->setName("Module2");
	temp=generator();
	this->data->setFirst(temp);
	temp=generator();
	this->data->setSecond(temp);
	p.set_value(data);
}
#endif
