#ifndef MODULE1_CPP
#define MODULE1_CPP
#include "DataPOJO.h"
#include "BaseModule.h"
#include "Module1.h"
#include<random>
#include<future>
#include<thread>
#include<chrono>
using namespace std;

//Default constructor of class BaseModule
Module1::Module1()
{
	this->data = new DataPOJO();
}

//This Method is the required overridden run() method according to the assignment.
//It has two parameters:
//-> first one is promise that will store and return the value as a DataPOJO Object when the task is completed
//-> second one is the seed that is used by PRNG of this Module and is generated by the PRNG in main
void Module1::run(promise<DataPOJO*> p,long long seed)
{
	long long temp;//Just a temporary value
	mt19937 generator (seed);//the PRNG of this Module
	this->data->setName("Module1");
	temp=generator();
	this->data->setFirst(temp);
	temp=generator();
	this->data->setSecond(temp);
	this_thread::sleep_for (chrono::seconds(5));//here we just generate a delay of 5 seconds
	p.set_value(data);
}
#endif
